/* Inserting Mock values into DB to test*/


INSERT INTO MASSEY_AUTHOR VALUES("61120",'Eskimo'	,'Bobbison'	,'Full'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61121",'Sam'	,'Bobbison'	,Null	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61122",'Edward'	,'Gosling'	,'Risk'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61123",'Alan'	,'Lau'		,'Mono'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61124",'Daniel'	,'Walmsley'	,'Sack'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61125",'Fleur'	,'Carman'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61126",'A'	,'Carmen'	,'Darthvader'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61127",'C'	,'Punjab'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61128",'Z'	,'Samagae'	,'C'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61129",'T'	,'Williamson'	,'Z'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61130",'P'	,'Sackley'	,'Rage'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61131",'Q'	,'Boric'	,'Machines'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61132",'Esky'	,'Harte'	,Null	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61133",'Sophie'	,'Canning'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61134",'C'	,'Canning'	,'Ceaser'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61135",'Alex'	,'Gibson'	,'S'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61136",'Q'	,'Singh'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61137",'Good'	,'Archer'	,'Homer'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61138",'Poppie'	,'Daphine'	,'D'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61139",'Richard','Mccaw'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61140",'T'	,'Umaga'	,'A'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61141",'Robin'	,'Smith'	,'A'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61142",'Cloud'	,'Smithy'	,'A'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61143",'Squall'	,'Burns'	,'C'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61144",'Zidane'	,'Anderson'	,'D'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61145",'Selphie','Trinity'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61146",'Dagger'	,'Morpheous'	,Null	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61147",'Jens'	,'Dietrach'	,'Fuh'	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61148",'R'	,'Permit'	,Null	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61149",'Names'	,'Noddy'	,'Damn'	,'Student','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61150",'N'	,'Samlee'	,Null	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61151",'C'	,'Bobbison'	,Null	,'Professor','SEAT','Science');
INSERT INTO MASSEY_AUTHOR VALUES("61152",'D'	,'Bobbison'	,'C'	,'Professor','SEAT','Science');


/*Some values may never be gotten if are found in above table first! Nothing can be done about this, */
INSERT INTO MISC_AUTHOR VALUES("0961120",'Eskimo'	,	'Bobbison'	,'C'	,'Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0961121",'D'		,'Bobbison'	,Null	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0961122",'E'		,'Gos'		,'Nama'	,'Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0861123",'Alan'		,'Laur'		,'P'	,'Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0861124",'D'		,'Samson'	,'Sack'	,'Victoria University'	);
INSERT INTO MISC_AUTHOR VALUES("0861125",'F'		,'Carman'	,Null	,'Singapore University'	); 
INSERT INTO MISC_AUTHOR VALUES("0461126",'D'		,'Carmen'	,Null	,'Singapore University'	);
INSERT INTO MISC_AUTHOR VALUES("0961127",'G'		,'Punjabby'	,Null	,'Singapore University'	);
INSERT INTO MISC_AUTHOR VALUES("0161128",'Z'		,'Reptor'	,'C'	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0361129",'D'		,'Williamson'	,'Z'	,'Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0461130",'L'		,'Sackley'	,'R' 	,'Tokoyo University'	);
INSERT INTO MISC_AUTHOR VALUES("0561131",'Q'		,'Bosling'	,'M' 	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0461132",'Boris'		,'Harte'	,Null	,'Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0961133",'Anna'		,'Canning'	,Null	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0861134",'F'		,'Canning'	,'Ceaser','Dublin University'	);
INSERT INTO MISC_AUTHOR VALUES("0761135",'Alex'		,'Bleh'		,'S'	,'Victoria University'	);
INSERT INTO MISC_AUTHOR VALUES("0461136",'Q'	,	'Sang'		,Null	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0561136",'Good'	,	'Archery'	,'Homer','Victoria University'	); 
INSERT INTO MISC_AUTHOR VALUES("0661138",'Z'	,	'Daphine'	,'D'	,'Dublin University'	); 
INSERT INTO MISC_AUTHOR VALUES("0261139",'R'	,	'Mccaw'		,Null	,'Tokoyo University'	);
INSERT INTO MISC_AUTHOR VALUES("0061140",'T'	,	'Umagan'		,'A'	,'Kyoto University'	);
INSERT INTO MISC_AUTHOR VALUES("0061141",'C'	,	'Smith'		,'A'	,'Victoria University'	);
INSERT INTO MISC_AUTHOR VALUES("0761142",'Cloud'	,'Smithers'	,'A'	,'Kyoto University'	);
INSERT INTO MISC_AUTHOR VALUES("0561143",'Squall'	,'Burns'	,'D'	,'Singapore University'	);
INSERT INTO MISC_AUTHOR VALUES("0161144",'Zidane'	,'Anderson'	,Null	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0261145",'D'	,	'Trinity'	,Null	,'Tokoyo University'	);
INSERT INTO MISC_AUTHOR VALUES("0461146",'Dagger'	,'Morpheous'	,'Socks','Tokoyo University'	);
INSERT INTO MISC_AUTHOR VALUES("0661147",'J'		,'Diettrach'	,Null	,'Singapore University'	);
INSERT INTO MISC_AUTHOR VALUES("0961148",'C'		,'Permit'	,Null	,'Victoria University'	);
INSERT INTO MISC_AUTHOR VALUES("0661149",'Plod'		,'Noddy'	,Null	,'Cali University'	);
INSERT INTO MISC_AUTHOR VALUES("0761150",'Anvil'	,'Samlee'	,Null	,'Singapore University'	);
INSERT INTO MISC_AUTHOR VALUES("0761151",'Cam'		,'Bobbison'	,'Dan'	,'Victoria University'	);
INSERT INTO MISC_AUTHOR VALUES("0461152",'Dougal'	,'Bobbisony'	,'C'	,'Singapore University'	);

INSERT INTO PUBLICATION VALUES ('10.1016/j.tcs.2010.07.007');
INSERT INTO PUBLICATION VALUES ('10.1016/j.websem_2006.11.007');
INSERT INTO PUBLICATION VALUES ('10.3998/3336451.0009.101');
INSERT INTO PUBLICATION VALUES ('10.3998/a.web.dfsa9.101');
INSERT INTO PUBLICATION VALUES ('10.5569/a.web.dfsa9.asd.15431');
INSERT INTO PUBLICATION VALUES ('10.536/346451.0937n.10892471');
INSERT INTO PUBLICATION VALUES ('10.35896/9836451.913835.102131');
INSERT INTO PUBLICATION VALUES ('10.90908/246451.fgjkil.2351');
INSERT INTO PUBLICATION VALUES ('10.4579890/082475.^sfkjd".97953');
INSERT INTO PUBLICATION VALUES ('10.982357/908312.GKDStuiw.o3i52');
INSERT INTO PUBLICATION VALUES ('10.90835/33451.(.98320');
